
  # First remove any repository if needed
  - include: remove_percona_repository.yml

  # Add an Apt signing key, will not download if present
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"

  # Add Percona testing repository
  - name: add the deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ ansible_lsb.codename }} testing' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: add the yum percona repos for centos 5
    command: "{{ item }}"
    with_items:
      - curl -o ~/percona-release-0.1-3.noarch.rpm --limit-rate 200k http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
      - rpm -ivH ~/percona-release-0.1-3.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: add the yum percona repos for centos 6 and 7
    yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "5"

  - name: change the default repo in yum repo file to testing
    command: "{{ item }}"
    with_items:
      - sed -r -e -i '/^baseurl = http:\/\/repo.percona.com\/release\/\$releasever\/RPMS\/\$basearch$/ { n ; s/^enabled = .*$/enabled = 0/ }' /etc/yum.repos.d/percona-release.repo.rpmsave
      - sed -r -e -i '/^baseurl = http:\/\/repo.percona.com\/release\/\$releasever\/RPMS\/noarch$/ { n ; s/^enabled = .*$/enabled = 0/ }' /etc/yum.repos.d/percona-release.repo.rpmsave
      - sed -r -e -i '/^baseurl = http:\/\/repo.percona.com\/testing\/$releasever\/RPMS\/\$basearch$/ { n ; s/^enabled = .*$/enabled = 1/ }' /etc/yum.repos.d/percona-release.repo.rpmsave
      - sed -r -e -i '/^baseurl = http:\/\/repo.percona.com\/testing\/\$releasever\/RPMS\/noarch$/ { n ; s/^enabled = .*$/enabled = 1/ }' /etc/yum.repos.d/percona-release.repo.rpmsave
