
#  - name: setup throttling for yum
#    command: echo "throttle=300k" >> /etc/yum.conf
#    when: ansible_os_family == "RedHat"

#  - name: setup throttling for apt
#    copy: src=../apt-throttling
#          dest=/etc/apt/apt.conf.d/
#          mode=0640 owner=root group=root
#    when: ansible_os_family == "Debian"

  - name: setup epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: setup epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

### remove this when centos5 is EOL
  - name: download package-testing repo with wget
    command: "{{ item }}"
    with_items:
    - rm -rf /package-testing
    - wget -O master.zip https://github.com/Percona-QA/package-testing/archive/master.zip
    - unzip master.zip
    - rm -f master.zip
    - mv package-testing-master /package-testing
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: fixes for centos5 repositories
    command: /package-testing/centos5.sh
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"
### end remove

  - name: install needed packages for running tests with apt
    apt: name="{{ item }}" update_cache=yes
    with_items:
    - pv
    - unzip
    - wget
    when: ansible_os_family == "Debian"

  - name: install sysv-rc-conf package for running tests with apt
    apt: name="{{ item }}" update_cache=no
    with_items:
    - sysv-rc-conf
    when: ansible_os_family == "Debian" and (ansible_distribution_release == "precise" or ansible_distribution_release == "trusty" or ansible_distribution_release == "wheezy")

  - name: update systemd-sysv integration on debian/ubuntu
    apt: name="{{ item }}" update_cache=yes state=latest
    with_items:
    - systemd-sysv
    when: ansible_os_family == "Debian" and ansible_distribution_release != "precise" and ansible_distribution_release != "trusty" and ansible_distribution_release != "wheezy"

  - name: install needed packages for running tests with yum
    yum: name="{{ item }}" state=latest
    with_items:
    - pv
    - libselinux-python
    - unzip
    - wget
    when: ansible_os_family == "RedHat"

  - name: register SLES for updates
    command: suse_register -a email="@@SLES_REG_EMAIL@@" -a regcode-sles=@@SLES_REG_CODE@@
    when: ansible_os_family == "Suse"

  # - name: setup SDK repo on SLES
  #   zypper: name="{{ item }}" state=present
  #   with_items:
  #   - /package-testing/sle-sdk-release-11.4-1.55.x86_64.rpm
  #   - /package-testing/sle-sdk-release-SDK-11.4-1.55.x86_64.rpm
  #   when: ansible_os_family == "Suse"

  - name: install needed packages for running tests with zypper
    zypper: name="{{ item }}" state=latest
    with_items:
    - wget
    - unzip
    when: ansible_os_family == "Suse"

  - name: download package-testing repo with wget
    command: "{{ item }}"
    with_items:
    - rm -rf /package-testing
    - rm -f master.zip
    - wget --no-check-certificate -O master.zip https://github.com/Percona-QA/package-testing/archive/master.zip
    - unzip master.zip
    - rm -f master.zip
    - mv package-testing-master /package-testing

  - name: install latest bats from github
    command: "{{ item }}"
    with_items:
    - rm -f master.zip
    - wget --no-check-certificate -O master.zip https://github.com/sstephenson/bats/archive/master.zip
    - unzip master.zip
    - rm -f master.zip
    - bats-master/install.sh /usr/local
    - rm -rf bats-master

  - name: remove gnupg to fix issue with importing key on debian stretch
    apt: name="{{ item }}" update_cache=no state=absent
    with_items:
    - gnupg
    when: ansible_os_family == "Debian" and ansible_distribution_release == "stretch"

  - name: install gnupg2 to fix issue with importing key on debian stretch
    apt: name="{{ item }}" update_cache=no
    with_items:
    - gnupg2
    when: ansible_os_family == "Debian" and ansible_distribution_release == "stretch"
