
  - name: setup throttling for yum
    command: echo "throttle=1M" >> /etc/yum.conf
    when: ansible_os_family == "RedHat"

  - name: setup throttling for apt
    template: src=../templates/apt.throttling
              dest=/etc/apt/apt.conf.d/lowerspeed
              mode=0640 owner=root group=root
    when: ansible_os_family == "Debian"

  - name: install git with apt
    apt: name={{item}} update_cache=yes
    with_items:
    - git
    when: ansible_os_family == "Debian"

  - name: install git with yum
    yum: name={{item}} state=present
    with_items:
    - git
    when: ansible_os_family == "RedHat"
    
  - git: repo=https://github.com/Percona-QA/package-testing
         dest=/package-testing
         depth=1
