
#  - name: setup throttling for yum
#    command: echo "throttle=300k" >> /etc/yum.conf
#    when: ansible_os_family == "RedHat"

#  - name: setup throttling for apt
#    copy: src=../apt-throttling
#          dest=/etc/apt/apt.conf.d/
#          mode=0640 owner=root group=root
#    when: ansible_os_family == "Debian"

  - name: epel 5 repo
    command: "{{ item }}"
    with_items:
      - curl -o ~/epel-release-latest-5.noarch.rpm --limit-rate 200k https://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm
      - rpm -ivH ~/epel-release-latest-5.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: epel 6 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: epel 7 repo
    yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install needed packages with apt
    apt: name={{item}} update_cache=yes
    with_items:
    - git
    - pv
    when: ansible_os_family == "Debian"

  - name: install needed packages with yum
    yum: name={{item}} state=present
    with_items:
    - git
    - curl
    - pv
    - libselinux-python
    when: ansible_os_family == "RedHat"
    
  - git: repo=https://github.com/Percona-QA/package-testing
         dest=/package-testing
         depth=1

  - name: download and extract world database
    command: "{{ item }}"
    with_items:
      - curl -o /package-testing/world.sql.gz --limit-rate 200k http://downloads.mysql.com/docs/world.sql.gz
      - gunzip /package-testing/world.sql.gz

