
  - name: setup throttling for yum
    command: echo "throttle=200k" >> /etc/yum.conf
    when: ansible_os_family == "RedHat"

  - name: setup throttling for apt
    copy: src=../apt-throttling
          dest=/etc/apt/apt.conf.d/
          mode=0640 owner=root group=root
    when: ansible_os_family == "Debian"

  - name: install git with apt
    apt: name={{item}} update_cache=yes
    with_items:
    - git
    when: ansible_os_family == "Debian"

  - name: install git with yum
    yum: name={{item}} state=present
    with_items:
    - git
    when: ansible_os_family == "RedHat"
    
  - git: repo=https://github.com/Percona-QA/package-testing
         dest=/package-testing
         depth=1

  - name: download and extract world database
    command: "{{ item }} chdir=/package-testing/"
    with_items: 
      - curl -O --limit-rate 200k http://downloads.mysql.com/docs/world.sql.gz
      - gunzip world.sql.gz

