---
# This playbook sets up the percona repo and installs Percona Server 5.7

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - include: ../tasks/test_prep.yml

  # Add an Apt signing key, will not download if present
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"

  - name: add the deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present update_cache=yes
    when: ansible_os_family == "Debian"

  - name: add the yum percona repos for centos 5
    command: "{{ item }}"
    with_items:
      - curl -o ~/percona-release-0.1-3.noarch.rpm --limit-rate 200k http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
      - rpm -ivH ~/percona-release-0.1-3.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: add the yum percona repos for centos 6 and 7
    yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version != "5"

  - name: install Percona Toolkit deb packages
    apt: name={{item}} update_cache=yes
    with_items:
    - percona-toolkit
    when: ansible_os_family == "Debian"

  - name: install Percona XtraBackup deb packages
    apt: name={{item}} update_cache=no
    with_items:
    - percona-xtrabackup-24
    when: ansible_os_family == "Debian"

  - name: install Percona Server deb packages
    apt: name={{item}} update_cache=no
    with_items:
    - percona-server-server-5.7
    - percona-server-test-5.7
    - percona-server-5.7-dbg
    - percona-server-source-5.7
    - percona-server-tokudb-5.7
    when: ansible_os_family == "Debian"

  - name: install Percona Toolkit packages in centos
    yum: name={{item}} state=present enablerepo=percona-testing-x86_64
    with_items:
    - percona-toolkit
    when: ansible_os_family == "RedHat"

  - name: install Percona XtraBackup packages in centos
    yum: name={{item}} state=present enablerepo=percona-testing-x86_64
    with_items:
    - percona-xtrabackup-24
    when: ansible_os_family == "RedHat"

  - name: install Percona Server packages in centos
    yum: name={{item}} state=present enablerepo=percona-testing-x86_64
    with_items:
    - Percona-Server-server-57
    - Percona-Server-test-57
    - Percona-Server-57-debuginfo
    - Percona-Server-devel-57
    - Percona-Server-tokudb-57
    when: ansible_os_family == "RedHat"

  - name: start the MySQL service
    command: service mysql start
    when: ansible_os_family == "RedHat"

  - name: set root password
    command: /package-testing/setpass_57.sh
    when: ansible_os_family == "RedHat"

  - name: copy .my.cnf
    template: src=../templates/my_57.j2
              dest=/root/.my.cnf
              mode=0640 owner=root group=root
    when: ansible_os_family == "RedHat"

  - name: disable selinux on centos7 for TokuDB to work
    command: setenforce 0
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: install tokudb
    command: /usr/bin/ps_tokudb_admin --enable

  - name: install plugins
    command: /package-testing/plugins_test_57.sh
