---
# This playbook sets up the mongodb-org repo and installs mongodb

- hosts: all
  sudo: yes

  tasks:
  # Add the mongodb apt signing key, will not download if present
  - apt_key: id=7F0CEB10 keyserver=keyserver.ubuntu.com state=present
    when: ansible_os_family == "Debian"
  - name: add the mongo ubuntu repo
    apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu {{ansible_lsb.codename}}/mongodb-org/3.0 multiverse' state=present update_cache=yes
    when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"
  - name: add the mongo debian repo
    apt_repository: repo='deb http://repo.mongodb.org/apt/debian {{ansible_lsb.codename}}/mongodb-org/3.0 main' state=present update_cache=yes
    when: ansible_os_family == "Debian" and ansible_distribution == "Debian"
  # Add the Percona apt signing key, will not download if present
  - apt_key: id=CD2EFD2A keyserver=keys.gnupg.net state=present
    when: ansible_os_family == "Debian"
  - name: add the deb repo
    apt_repository: repo='deb http://repo.percona.com/apt {{ansible_lsb.codename}} main' state=present update_cache=yes
    when: ansible_os_family == "Debian"
 # - name: copy apt-cacher-ng proxy file
 #   when: ansible_os_family == "Debian"
  - name: install deb packages 
    apt: name={{item}} update_cache=yes
    with_items: 
    - vim
    - pv
 #  - mongodb-org
 #  - percona-server-mongodb
    when: ansible_os_family == "Debian"
  - name: epel 6 repo
    sudo: yes
    yum: name=https://anorien.csc.warwick.ac.uk/mirrors/epel/6/i386/epel-release-6-8.noarch.rpm state=present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  - name: add the yum percona repos
    sudo: yes
    yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm
    when: ansible_os_family == "RedHat"
  - name: install packages in centos
    yum: name={{item}} state=present
    with_items:
    - libselinux-python
    - pv
    when: ansible_os_family == "RedHat"
  - name: add the mongo rpm repo
    copy: src=/home/hrvoje/worktable/package-testing/mongodb-org-3.0.repo dest=/etc/yum.repos.d/
    when: ansible_os_family == "RedHat"
  - name: install mongodb-org 
    yum: name=mongodb-org state=present
    when: ansible_os_family == "RedHat"
# - name: remove the deb repo
#   apt_repository: repo='deb [arch=amd64] http://192.168.5.9/apt {{ansible_lsb.codename}} main' state=absent update_cache=yes
#   when: ansible_os_family == "Debian"
# - name: add the testing deb repo
#   apt_repository: repo='deb [arch=amd64] http://192.168.5.9/apt {{ansible_lsb.codename}} main testing' state=present update_cache=yes
#   when: ansible_os_family == "Debian"
# - name: apt-get upgrade
#   apt: upgrade=safe
#   when: ansible_os_family == "Debian"
