---
# This playbook does following:
#   enables Percona testing repository
#   installs PSMDB 3.4
#   does some tests

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

  - name: include tasks for enabling test repo
    include: ../tasks/enable_testing_repo.yml

  - name: install Percona Server for MongoDB 3.4 new deb packages
    apt: name={{item}} update_cache=yes state=latest
    with_items:
    - percona-server-mongodb-34
    - percona-server-mongodb-34-dbg
    when: ansible_os_family == "Debian"

  - name: install Percona Server for MongoDB 3.4 new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-Server-MongoDB-34
    - Percona-Server-MongoDB-34-debuginfo
    when: ansible_os_family == "RedHat"

  - name: start mongod with init script
    command: /etc/init.d/mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

  - name: start mongod with service
    command: service mongod start
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

  - name: start mongod with systemctl
    command: systemctl start mongod
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

  - name: check that PSMDB 3.4 package versions are correct
    command: /package-testing/package_check.sh psmdb34

  - name: test SE change, import data, restart service
    command: /package-testing/psmdb_test.sh 3.4

  - name: run bats tests for mongo init scripts
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: install numactl package on debian
    apt: name={{item}} update_cache=no state=latest
    with_items:
    - numactl
    when: ansible_os_family == "Debian"

  - name: install numactl package on centos
    yum: name={{item}} state=latest
    with_items:
    - numactl
    when: ansible_os_family == "RedHat"

  - name: run bats tests for mongo init scripts after numactl install
    command: /usr/local/bin/bats /package-testing/bats/mongo-init-scripts.bats

  - name: start mongod service
    service: name=mongod state=started

  - name: remove Percona Server for MongoDB 3.4 deb packages
    apt: name={{item}} update_cache=no state=absent
    with_items:
    - percona-server-mongodb-34-server
    when: ansible_os_family == "Debian"

  - name: remove Percona Server for MongoDB 3.4 rpm packages
    yum: name={{item}} state=absent
    with_items:
    - Percona-Server-MongoDB-34-server
    when: ansible_os_family == "RedHat"

  - name: check if process is stopped after package removal
    command: /package-testing/check_running.sh mongodb stopped
