---
# This playbook does following:
#   downloads PSMDB 3.4 new SLES packages from webpage
#   installs PSMDB 3.4
#   does some tests
- import_playbook: test_prep.yml

- hosts: all
  become: true
  become_method: sudo
  vars:
    psmdb_prefix: "Percona-Server-MongoDB-34-"
    psmdb_suffix: ".sles12.x86_64.rpm"
    psmdb_ver: "3.4.4-1.4"
    new_dl_link: "https://www.percona.com/redir/downloads/TESTING/sles12/"

  tasks:
  - name: include tasks for test env setup
    include: ../tasks/test_prep.yml

  - name: download Percona Server for MongoDB 3.4 SLES packages
    command: "{{ item }}"
    with_items:
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}mongos-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}server-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}shell-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}tools-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}debugsource-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}mongos-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}server-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}shell-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}"
    - wget "{{ new_dl_link }}{{ psmdb_prefix }}tools-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}"

  - name: install Percona Server for MongoDB 3.4 new SLES packages
    command: zypper -n install "{{ psmdb_prefix }}mongos-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}shell-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}tools-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}server-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}debugsource-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}mongos-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}server-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}shell-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}" "{{ psmdb_prefix }}tools-debuginfo-{{ psmdb_ver }}{{ psmdb_suffix }}"

  - name: start mongod with service
    service: name=mongod state=started

  - name: check that PSMDB 3.4 package versions are correct
    command: /package-testing/package_check.sh psmdb34

  - name: test SE change, import data, restart service
    command: /package-testing/psmdb_test.sh 3.4
