---
# This playbook upgrades the PXC node to the latest available version in testing repo

- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: include tasks for enabling testing repo
    include: ../tasks/enable_testing_repo.yml

  - name: upgrade PXC 5.7 to new deb packages
    apt: name={{item}} update_cache=yes
    with_items:
    - percona-xtradb-cluster-full-57
    when: ansible_os_family == "Debian"

  - name: upgrade PXC 5.7 to new rpm packages
    yum: name={{item}} state=latest
    with_items:
    - Percona-XtraDB-Cluster-full-57
    when: ansible_os_family == "RedHat"
