---
# This playbook sets up the percona repo

- hosts: all

  tasks:
  - name: add the deb repo
    sudo: yes
    apt_repository: repo='deb [arch=amd64] http://repo.percona.com/apt {{ansible_lsb.codename}} main testing' state=present
    when: ansible_os_family == "Debian"
  - name: upgrade deb packages 
    sudo: yes
    apt: update_cache=yes upgrade=safe
    when: ansible_os_family == "Debian"
  - name: upgrade packages in centos
    sudo: yes
    yum: name=Percona-Server-server-55 enablerepo=percona-testing-x86_64 state=latest
    when: ansible_os_family == "RedHat"
